### ISSUE TITLE
could you please give me some advice about this problem? 

### ISSUE THREAD

**Issue by Maoloveresearch** [philipperemy/very-deep-convnets-raw-waveforms#3]
Traceback (most recent call last):
  File "model_run.py", line 52, in <module>
    x_tr, y_tr = data_reader.get_all_training_data()
  File "/home/yanan/very-deep-convnets-raw-waveforms/model_data.py", line 32, in get_all_training_data
    return DataReader._get_data(self.train_files)
  File "/home/yanan/very-deep-convnets-raw-waveforms/model_data.py", line 47, in _get_data
    load_into(filename, x, y)
  File "/home/yanan/very-deep-convnets-raw-waveforms/model_data.py", line 43, in load_into
    _y.append(int(audio_element['class_id']))
ValueError: invalid literal for int() with base 10: 'deep'

**Comment by philipperemy** [comment]
@Maoloveresearch I think you're using the code in the wrong way. First of all, can you run successfully the examples provided in the README?

**Comment by philipperemy** [comment]
Closed due to inactivity.
